'use strict';
const state={token:sessionStorage.getItem('securityedge_token')||'',overview:null,policies:null,rules:[],securityCursor:0,securityHasMore:false,selectedPolicy:'default',trend:[]};
const $=id=>document.getElementById(id);const fmt=n=>Number(n||0).toLocaleString();const pct=n=>`${(Number(n||0)*100).toFixed(1)}%`;const ms=n=>`${Number(n||0).toFixed(1)} ms`;const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(path,opts={}){const headers=new Headers(opts.headers||{});headers.set('Authorization',`Bearer ${state.token}`);if(opts.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');const res=await fetch(path,{...opts,headers});let data=null;try{data=await res.json()}catch{}if(res.status===401){lock();throw new Error('Invalid or expired admin token.')}if(!res.ok)throw new Error(data?.error?.message||`HTTP ${res.status}`);return data}
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2600)}
function lock(){$('login').classList.add('visible');$('live-dot').classList.remove('live');$('connection-label').textContent='Not connected';sessionStorage.removeItem('securityedge_token');state.token=''}
async function login(token){state.token=token;await api('/api/v1/session');sessionStorage.setItem('securityedge_token',token);$('login').classList.remove('visible');$('live-dot').classList.add('live');$('connection-label').textContent='Connected';await refreshAll()}
function setView(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));document.querySelectorAll('.nav-item').forEach(v=>v.classList.toggle('active',v.dataset.view===name));$('page-title').textContent=({overview:'Overview',security:'Security events',traffic:'Traffic & cache',routes:'Routes & origins',policies:'Policies',system:'System'})[name];if(name==='security')loadSecurity(true);if(name==='policies'&&!state.policies)loadPolicies();}
async function refreshAll(){try{const [overview,policies,rules]=await Promise.all([api('/api/v1/dashboard/overview'),api('/api/v1/policies'),api('/api/v1/rules')]);state.overview=overview;state.policies=policies;state.rules=rules.rules||[];renderAll();$('last-updated').textContent=`Updated ${new Date().toLocaleTimeString()}`;$('live-dot').classList.add('live')}catch(err){toast(err.message);$('live-dot').classList.remove('live')}}
function renderAll(){renderOverview();renderTraffic();renderRoutes();renderPolicies();renderSystem();renderRules();loadEdgeLogs()}
function renderOverview(){const o=state.overview||{},s=o.security_metrics||{},st=s.total||{},em=o.edgeproxy_metrics||{},et=em.total||{},es=o.edgeproxy_status||{};$('kpi-requests').textContent=fmt(et.requests);$('kpi-rps').textContent=`${Number(em.requests_per_second||0).toFixed(2)} req/s`;$('kpi-blocked').textContent=fmt((st.blocked||0)+(st.rate_limited||0));$('kpi-block-rate').textContent=`${pct(st.block_rate)} block rate`;$('kpi-detections').textContent=fmt(st.detections);$('kpi-detection-rate').textContent=`${pct(st.detection_rate)} detection rate`;$('kpi-cache').textContent=pct(et.cache_hit_ratio);$('kpi-cache-counts').textContent=`${fmt(et.cache_hits)} hits · ${fmt(et.cache_misses)} misses`;$('kpi-p95').textContent=ms(et.response_latency_ms?.p95);$('kpi-upstream').textContent=`${ms(et.upstream?.latency_ms?.average)} upstream avg`;const routes=es.routes||[],origins=routes.flatMap(r=>r.upstreams||[]),healthy=origins.filter(x=>x.healthy).length;$('kpi-origins').textContent=`${healthy}/${origins.length}`;$('kpi-routes').textContent=`${routes.filter(r=>r.ready).length}/${routes.length} routes ready`;state.trend.push({requests:et.requests||0,blocked:(st.blocked||0)+(st.rate_limited||0),time:Date.now()});if(state.trend.length>30)state.trend.shift();drawTrend();renderRuleBars(st.rules||{});renderSecurityRows($('recent-security'),o.security_logs?.entries||[],7)}
function drawTrend(){const c=$('trend-chart'),dpr=devicePixelRatio||1,w=c.clientWidth||600,h=240;c.width=w*dpr;c.height=h*dpr;const x=c.getContext('2d');x.scale(dpr,dpr);x.clearRect(0,0,w,h);x.strokeStyle='#25324c';x.lineWidth=1;for(let i=0;i<5;i++){const y=20+i*(h-40)/4;x.beginPath();x.moveTo(0,y);x.lineTo(w,y);x.stroke()}const max=Math.max(1,...state.trend.flatMap(p=>[p.requests,p.blocked]));const draw=(key,color)=>{x.strokeStyle=color;x.lineWidth=2;x.beginPath();state.trend.forEach((p,i)=>{const px=state.trend.length===1?w/2:i*(w/(state.trend.length-1));const py=h-20-(p[key]/max)*(h-40);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()};draw('requests','#67a6ff');draw('blocked','#ff7188')}
function renderRuleBars(rules){const entries=Object.entries(rules).sort((a,b)=>b[1]-a[1]).slice(0,7),el=$('rule-bars');if(!entries.length){el.className='bar-list empty';el.textContent='No detections yet.';return}el.className='bar-list';const max=entries[0][1];el.innerHTML=entries.map(([id,n])=>`<div class="bar-row"><span>${esc(id)}</span><div class="bar-track"><div class="bar-fill" style="width:${n/max*100}%"></div></div><strong>${fmt(n)}</strong></div>`).join('')}
function renderSecurityRows(el,entries,limit=100){const rows=entries.slice(0,limit);el.innerHTML=rows.length?rows.map(e=>`<tr><td>${esc(new Date(e.timestamp).toLocaleTimeString())}</td><td><span class="badge ${String(e.action).toLowerCase()}">${esc(e.action)}</span></td><td>${esc(e.route)}</td><td>${esc(e.client_ip)}</td><td><strong>${esc(e.method)}</strong> ${esc(e.path)}</td><td>${(e.rule_ids||[]).map(r=>`<span class="badge warn">${esc(r)}</span>`).join(' ')||'<span class="muted">—</span>'}</td><td>${fmt(e.score)}</td></tr>`).join(''):`<tr><td colspan="7" class="muted">No security events.</td></tr>`}
async function loadSecurity(reset){try{if(reset)state.securityCursor=0;const form=new FormData($('security-filters')),q=new URLSearchParams();for(const [k,v] of form)if(v)q.set(k,v);q.set('limit','100');if(state.securityCursor)q.set('before_sequence',state.securityCursor);const data=await api(`/api/v1/logs?${q}`);renderSecurityRows($('security-table'),data.entries||[],100);state.securityCursor=data.next_before_sequence||0;state.securityHasMore=!!data.has_more;$('older-security').disabled=!state.securityHasMore;$('security-count').textContent=`${data.returned||0} shown · ${data.retained||0} retained`}catch(err){toast(err.message)}}
function metricRows(items){return items.map(([k,v])=>`<div class="metric-row"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('')}
function renderTraffic(){const et=state.overview?.edgeproxy_metrics?.total||{};$('cache-stats').innerHTML=metricRows([['Hits',fmt(et.cache_hits)],['Misses',fmt(et.cache_misses)],['Stale',fmt(et.cache_stale)],['Bypasses',fmt(et.cache_bypasses)],['Stores',fmt(et.cache_stores)],['Hit ratio',pct(et.cache_hit_ratio)]]);const l=et.response_latency_ms||{};$('latency-stats').innerHTML=metricRows([['Average',ms(l.average)],['Minimum',ms(l.minimum)],['Maximum',ms(l.maximum)],['P50',ms(l.p50)],['P95',ms(l.p95)],['P99',ms(l.p99)]])}
async function loadEdgeLogs(){try{const d=await api('/api/v1/edgeproxy/logs?event=request_completed&limit=50');const el=$('edge-log-table'),rows=d.entries||[];el.innerHTML=rows.length?rows.map(e=>`<tr><td>${esc(new Date(e.timestamp).toLocaleTimeString())}</td><td><span class="badge ${e.status>=500?'error':e.status>=400?'warn':'allow'}">${e.status}</span></td><td><span class="badge ${String(e.cache_status).toLowerCase()}">${esc(e.cache_status||'—')}</span></td><td>${esc(e.route)}</td><td><strong>${esc(e.method)}</strong> ${esc(e.path)}</td><td>${ms(e.duration_ms)}</td><td>${esc(e.upstream||'—')}</td></tr>`).join(''):`<tr><td colspan="7" class="muted">No EdgeProxy logs.</td></tr>`}catch(err){$('edge-log-table').innerHTML=`<tr><td colspan="7" class="muted">${esc(err.message)}</td></tr>`}}
function renderRoutes(){
  const routes=state.overview?.edgeproxy_status?.routes||[];
  if(!routes.length){
    $('route-cards').innerHTML='<article class="panel"><p>No route status available.</p></article>';
    return;
  }
  $('route-cards').innerHTML=routes.map(r=>{
    const cache=r.cache
      ? metricRows([
          ['Cache entries',fmt(r.cache.entries)],
          ['Cache bytes',fmt(r.cache.bytes)],
          ['LRU evictions',fmt(r.cache.evictions)]
        ])
      : '<p class="muted">Cache disabled</p>';
    const origins=(r.upstreams||[]).map(u=>
      `<div class="origin"><span>${esc(u.url||u.upstream)}</span><span class="badge ${u.healthy?'ready':'error'}">${u.healthy?'healthy':'unhealthy'}</span></div>`
    ).join('');
    return `<article class="route-card"><div class="route-head"><h2>${esc(r.name)}</h2><span class="badge ${r.ready?'ready':'error'}">${r.ready?'READY':'NOT READY'}</span></div>${cache}<h3>Origins</h3>${origins}</article>`;
  }).join('');
}
async function loadPolicies(){state.policies=await api('/api/v1/policies');renderPolicies()}
function renderPolicies(){if(!state.policies)return;const scopes=$('policy-scopes'),routes=state.policies.routes||[];scopes.innerHTML=`<button data-policy="default" class="${state.selectedPolicy==='default'?'active':''}">Default policy</button>`+routes.map(r=>`<button data-policy="${esc(r.name)}" class="${state.selectedPolicy===r.name?'active':''}">${esc(r.name)}${state.policies.route_policies?.[r.name]?' · override':''}</button>`).join('');scopes.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.selectedPolicy=b.dataset.policy;renderPolicies()});const isDefault=state.selectedPolicy==='default',p=isDefault?state.policies.default_policy:(state.policies.effective_policies?.[state.selectedPolicy]||state.policies.default_policy),f=$('policy-form');$('policy-title').textContent=isDefault?'Default policy':`${state.selectedPolicy} policy`;$('delete-override').classList.toggle('hidden',isDefault||!state.policies.route_policies?.[state.selectedPolicy]);f.enabled.checked=!!p.enabled;f.mode.value=p.mode;f.anomaly_threshold.value=p.anomaly_threshold;f.max_inspection_body_bytes.value=p.max_inspection_body_bytes;f.inspect_request_body.checked=!!p.inspect_request_body;f.allowed_methods.value=(p.allowed_methods||[]).join(', ');f.excluded_path_prefixes.value=(p.excluded_path_prefixes||[]).join(', ');f.disabled_rules.value=(p.disabled_rules||[]).join(', ');f.rate_enabled.checked=!!p.rate_limit?.enabled;f.requests_per_second.value=p.rate_limit?.requests_per_second??20;f.burst.value=p.rate_limit?.burst??40;const select=$('purge-route');select.innerHTML=routes.map(r=>`<option value="${esc(r.name)}">${esc(r.name)}</option>`).join('')}
function csv(v){return v.split(',').map(x=>x.trim()).filter(Boolean)}
async function savePolicy(ev){ev.preventDefault();const base=state.selectedPolicy==='default'?state.policies.default_policy:(state.policies.effective_policies?.[state.selectedPolicy]||state.policies.default_policy),f=ev.currentTarget,p=structuredClone(base);p.enabled=f.enabled.checked;p.mode=f.mode.value;p.anomaly_threshold=Number(f.anomaly_threshold.value);p.max_inspection_body_bytes=Number(f.max_inspection_body_bytes.value);p.inspect_request_body=f.inspect_request_body.checked;p.allowed_methods=csv(f.allowed_methods.value).map(x=>x.toUpperCase());p.excluded_path_prefixes=csv(f.excluded_path_prefixes.value);p.disabled_rules=csv(f.disabled_rules.value).map(x=>x.toUpperCase());p.rate_limit.enabled=f.rate_enabled.checked;p.rate_limit.requests_per_second=Number(f.requests_per_second.value);p.rate_limit.burst=Number(f.burst.value);try{const path=state.selectedPolicy==='default'?'/api/v1/policies/default':`/api/v1/policies/${encodeURIComponent(state.selectedPolicy)}`;await api(path,{method:'PUT',body:JSON.stringify(p)});$('policy-result').textContent='Policy saved.';await loadPolicies();toast('Policy saved')}catch(err){$('policy-result').textContent=err.message}}
function renderSystem(){const sm=state.overview?.security_metrics||{},ss=state.overview?.security_logs||{},edgeStatus=state.overview?.edgeproxy_status_code;$('security-system').innerHTML=metricRows([['Schema',sm.schema_version||'—'],['Uptime',`${fmt(sm.uptime_seconds)} s`],['In flight',fmt(sm.inflight)],['Retained security events',fmt(ss.retained)],['Dropped events',fmt(ss.dropped)]]);$('edge-system').innerHTML=metricRows([['Admin HTTP status',edgeStatus||'unavailable'],['Metrics schema',state.overview?.edgeproxy_metrics?.schema_version||'—'],['Uptime',`${fmt(state.overview?.edgeproxy_metrics?.uptime_seconds)} s`],['In flight',fmt(state.overview?.edgeproxy_metrics?.inflight)],['Ready routes',`${(state.overview?.edgeproxy_status?.routes||[]).filter(r=>r.ready).length}/${(state.overview?.edgeproxy_status?.routes||[]).length}`]])}
function renderRules(){$('rules-table').innerHTML=state.rules.map(r=>`<tr><td><span class="badge warn">${esc(r.id)}</span></td><td>${esc(r.name)}</td><td>${esc(r.category)}</td><td>${fmt(r.score)}</td><td>${esc(r.description)}</td></tr>`).join('')}
$('login-form').addEventListener('submit',async e=>{e.preventDefault();$('login-error').textContent='';try{await login($('token').value.trim())}catch(err){$('login-error').textContent=err.message}});$('logout').onclick=lock;$('refresh').onclick=refreshAll;document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>setView(b.dataset.go));$('security-filters').onsubmit=e=>{e.preventDefault();loadSecurity(true)};$('older-security').onclick=()=>loadSecurity(false);$('clear-security').onclick=async()=>{if(!confirm('Clear all retained SecurityEdge events?'))return;await api('/api/v1/logs',{method:'DELETE'});await loadSecurity(true);toast('Security events cleared')};$('policy-form').onsubmit=savePolicy;$('delete-override').onclick=async()=>{await api(`/api/v1/policies/${encodeURIComponent(state.selectedPolicy)}`,{method:'DELETE'});await loadPolicies();toast('Route override deleted')};$('purge-form').onsubmit=async e=>{e.preventDefault();const q=new URLSearchParams({route:$('purge-route').value});if($('purge-host').value.trim())q.set('host',$('purge-host').value.trim());if($('purge-path').value.trim())q.set('path_prefix',$('purge-path').value.trim());try{const d=await api(`/api/v1/edgeproxy/cache/purge?${q}`,{method:'POST'});$('purge-result').textContent=`Purged ${d.purged_entries} entries.`;toast('Cache purged');await refreshAll()}catch(err){$('purge-result').textContent=err.message}};$('reload-config').onclick=async()=>{await api('/api/v1/reload',{method:'POST'});await refreshAll();toast('Configuration reloaded')};window.addEventListener('resize',()=>state.overview&&drawTrend());
if(state.token)login(state.token).catch(()=>lock());setInterval(()=>{if(state.token)refreshAll()},5000);
